// ==UserScript==
// @name          BYPASS SHIELDTEAM || SHINCHAN
// @namespace     bypass.web.id
// @version       1
// @author        bypass.web.id
// @description   Bypass ad-links using the bypass.web.id API and get to your destination without ads!
// @match         *://mega-guy.com/*
// @match         *://loot-link.com/*
// @match         *://best-links.org/*
// @match         *://loot-links.com/*
// @match         *://megaspremium.com/*
// @match         *://lootdest.com/*
// @match         *://direct-links.net/*
// @match         *://risquemega.com/*
// @match         *://onlyfriends.club/*
// @match         *://onepiecered.co/*
// @match         *://multileaks.com/*
// @match         *://luvsquad-links.com/*
// @match         *://lootdest.org/*
// @match         *://free-leaks.com/*
// @match         *://goldmega.online/*
// @match         *://realiukzemydre.com/*
// @match         *://kmendation.com/*
// @match         *://lootlinks.co/*
// @match         *://onlyshare.info/*
// @match         *://leakplugs.com/*
// @match         *://nswfbox.com/*
// @match         *://eofmukindwo.com/*
// @match         *://op-packs.com/*
// @match         *://thedetective.online/*
// @match         *://forlinkmeg.com/*
// @match         *://thegoatpack.org/*
// @match         *://of-leaks.xyz/*
// @match         *://links.spacebin.in/*
// @match         *://supermeg.com/*
// @match         *://onlyfanessereloaded.com/*
// @match         *://fanzleaks.com/*
// @match         *://cemendemons.com/*
// @match         *://premiummegaz.com/*
// @match         *://thepremium.online/*
// @match         *://pasteebins.com/*
// @match         *://baddiezcentral.com/*
// @match         *://megazone.website/*
// @match         *://leak-pragmatic.com/*
// @match         *://megadumpz.com/*
// @match         *://thhaven.net/*
// @match         *://meg4fans.com/*
// @match         *://depravityweb.co/*
// @match         *://discordlink.cc/*
// @match         *://megashub.co/*
// @match         *://streamergirls.org/*
// @match         *://your-leaks.com/*
// @match         *://onlylinksmegas.xyz/*
// @match         *://pypy.spacebin.in/*
// @match         *://pypy.in/*
// @match         *://luvsquad-links.cmo/*
// @match         *://beast.net.in/*
// @match         *://hook.beast.net.in/*
// @match         *://all-fans.online/*
// @match         *://fansmega.com/*
// @match         *://worldpacks.co/*
// @match         *://night-hub.online/*
// @match         *://dailyofleaks.com/*
// @match         *://pkofs.com/*
// @match         *://offree90.com/*
// @match         *://megadropz.com/*
// @match         *://onlyfunlink.com/*
// @match         *://direct-links.org/*
// @match         *://leaks4you.com/*
// @match         *://onlylinksmegas.com/*
// @match         *://direct-link.net/*
// @match         *://downbadleaks.com/*
// @match         *://onlyfanscloud.com/*
// @match         *://missleakz.com/*
// @match         *://leakszone.online/*
// @match         *://links-loot.com/*
// @match         *://holyfanslinks.com/*
// @match         *://utopianleaks.com/*
// @match         *://megavip.store/*
// @match         *://drlinker.com/*
// @match         *://baddiesheaven.com/*
// @match         *://of4lm-links.com/*
// @match         *://holedonly.store/*
// @match         *://lootlinks.com/*
// @match         *://free-content.pro/*
// @match         *://milky-center.com/*
// @match         *://megaofs.com/*
// @match         *://bleleadersto.com/*
// @match         *://link-target.org/*
// @match         *://daughablelea.com/*
// @match         *://mymegalinks.com/*
// @match         *://heroslut.com/*
// @match         *://tonordersitye.com/*
// @match         *://vip-linknetwork.com/*
// @match         *://birdbiss.com/*
// @match         *://loot-labs.com/*
// @match         *://lootlabs.com/*
// @match         *://link-hub.net/*
// @match         *://locconnect.com/*
// @match         *://premiumstashdrop.com/*
// @match         *://lootdest.info/*
// @match         *://of-area.com/*
// @match         *://link-target.net/*
// @match         *://megalnk.com/*
// @match         *://lootlink.org/*
// @match         *://nsfwcherry.com/*
// @match         *://cherrypacks.online/*
// @match         *://hotstars-leaks.com/*
// @match         *://onlymega.co/*
// @match         *://hanimeturks.com/*
// @match         *://dailyleakz.com/*
// @match         *://content-hub.club/*
// @match         *://dailyadultmegas.com/*
// @match         *://oui-chu.com/*
// @match         *://megalinks.one/*
// @match         *://starleakz.com/*
// @match         *://babeslink.click/*
// @match         *://ofgirls3x.com/*
// @match         *://pnp-drops.me/*
// @match         *://nsfw-paradise.club/*
// @match         *://key-access.co/*
// @match         *://leaksmix.com/*
// @match         *://sensual-leaks.com/*
// @match         *://ofhub-leaks.com/*
// @match         *://onlyforfan.online/*
// @match         *://sweetjuice-mega.com/*
// @match         *://crip-hub.com/*
// @match         *://leaksfreeday.com/*
// @match         *://thotshaven.online/*
// @match         *://mega-leaked.com/*
// @match         *://beautifulgirls.social/*
// @match         *://tavernleaks.com/*
// @match         *://nudeleaksteenz.com/*
// @match         *://slutywet.com/*
// @match         *://leakutopia.site/*
// @match         *://secret-packs.com/*
// @match         *://attiktok22.com/*
// @match         *://pancakes-leaks.com/*
// @match         *://diamond-leaks.com/*
// @match         *://lewd-leaks.com/*
// @match         *://ftbleaks.net/*
// @match         *://thepytheaven.org/*
// @match         *://of-region.online/*
// @match         *://admiregirls-byme.com/*
// @match         *://mzehoney12.com/*
// @match         *://herplace.online/*
// @match         *://megaplugleaks.com/*
// @match         *://of-kingdom.com/*
// @match         *://onlyfansmegafolder.com/*
// @match         *://links.spacebin.in/*
// @match         *://adfoc.us/*
// @match         *://boost.ink/*
// @match         *://cuty.io/*
// @match         *://www.cuty.io/*
// @match         *://cety.app/*
// @match         *://www.cety.app/*
// @match         *://linkvertise.com/*/*
// @match         *://mboost.me/*
// @match         *://bst.gg/*
// @match         *://booo.st/*
// @match         *://mendationforc.info/*
// @match         *://paster.so/*
// @match         *://paster.gg/*
// @match         *://rekonise.com/*
// @match         *://social-unlock.com/*
// @match         *://www.social-unlock.com/*
// @match         *://socialwolvez.com/*
// @match         *://sub2get.com/*
// @match         *://www.sub2get.com/*
// @match         *://sub2unlock.com/*
// @match         *://sub2unlock.io/*
// @match         *://sub2unlock.net/*
// @match         *://sub2unlock.online/*
// @match         *://sub2unlock.top/*
// @match         *://sub4unlock.pro/*
// @match         *://sub4unlock.com/*
// @match         *://sub4unlock.io/*
// @match         *://subfinal.com/*
// @match         *://unlocknow.net/*
// @match         *://v.gd/*
// @match         *://work.ink/*
// @match         *://www.work.ink/*
// @match         *://workink.net/*
// @match         *://r.work.ink/*
// @match         *://workink.one/*
// @match         *://workink.me/*
// @match         *://ytsubme.com/*
// @match         *://www.ytsubme.com/*
// @match         *://esohasl.net/*
// @match         *://rbscripts.net/*
// @match         *://link.rbscripts.net/*
// @downloadURL   https://raw.githubusercontent.com/sauma1/userscript/refs/heads/main/bypass-shield.user.js 
// @updateURL     https://raw.githubusercontent.com/sauma1/userscript/refs/heads/main/bypass-shield.user.js 
// @homepageURL   https://bypass.web.id
// @run-at document-start
// ==/UserScript==

apiKey = 'MASUKAN API KEY MU';

countDelay = 0;

function _0x2ebf(_0x567aab,_0x33e3d5){const _0x4e15fa=_0x4e15();return _0x2ebf=function(_0x2ebf85,_0x5654fb){_0x2ebf85=_0x2ebf85-0x1ef;let _0x3a2b5f=_0x4e15fa[_0x2ebf85];return _0x3a2b5f;},_0x2ebf(_0x567aab,_0x33e3d5);}(function(_0x5ca655,_0xdb4ed4){const _0x5366fd=_0x2ebf,_0x3d19ce=_0x5ca655();while(!![]){try{const _0x374aee=-parseInt(_0x5366fd(0x1f4))/0x1*(-parseInt(_0x5366fd(0x1ef))/0x2)+-parseInt(_0x5366fd(0x1f6))/0x3*(parseInt(_0x5366fd(0x1fc))/0x4)+-parseInt(_0x5366fd(0x1fa))/0x5*(parseInt(_0x5366fd(0x1f1))/0x6)+-parseInt(_0x5366fd(0x1f9))/0x7+-parseInt(_0x5366fd(0x1f2))/0x8*(parseInt(_0x5366fd(0x1f7))/0x9)+parseInt(_0x5366fd(0x1f5))/0xa*(-parseInt(_0x5366fd(0x1f8))/0xb)+parseInt(_0x5366fd(0x1fb))/0xc;if(_0x374aee===_0xdb4ed4)break;else _0x3d19ce['push'](_0x3d19ce['shift']());}catch(_0x197884){_0x3d19ce['push'](_0x3d19ce['shift']());}}}(_0x4e15,0x36c5d),(function(){const _0x498acc=_0x2ebf,_0x17b18a={'BrhSW':function(_0x3c1095,_0x42118e){return _0x3c1095(_0x42118e);}},_0x4eb893=_0x498acc(0x1f0);_0x17b18a[_0x498acc(0x1f3)](eval,_0x17b18a[_0x498acc(0x1f3)](atob,_0x4eb893));}()));function _0x4e15(){const _0x2ee253=['22fKogsF','964544sQbPXd','20jDemEb','12544488mwPrde','28uxRtsl','69890ubjYvq','ZnVuY3Rpb24gZGVsYXkobXMpIHsKICAgIHJldHVybiBuZXcgUHJvbWlzZShyZXNvbHZlID0+IHNldFRpbWVvdXQocmVzb2x2ZSwgbXMpKTsKICB9Cihhc3luYyAoKSA9PiB7CiAgICBjb25zdCBvcmlnaW5hbENyZWF0ZUVsZW1lbnQgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50LmJpbmQoZG9jdW1lbnQpOwogICAgZG9jdW1lbnQuY3JlYXRlRWxlbWVudCA9IGZ1bmN0aW9uKGVsZW1lbnROYW1lKSB7CiAgICAgICAgY29uc3QgZWxlbWVudCA9IG9yaWdpbmFsQ3JlYXRlRWxlbWVudChlbGVtZW50TmFtZSk7CiAgICAgICAgaWYgKGVsZW1lbnROYW1lLnRvTG93ZXJDYXNlKCkgPT09ICdzY3JpcHQnKSB7CiAgICAgICAgICAgIGVsZW1lbnQuc2V0QXR0cmlidXRlKCd0eXBlJywgJ3RleHQvcGxhaW4nKTsKICAgICAgICB9CiAgICAgICAgcmV0dXJuIGVsZW1lbnQ7CiAgICB9OwoKICAgIGNvbnN0IHVybFBhcmFtcyA9IG5ldyBVUkxTZWFyY2hQYXJhbXMod2luZG93LmxvY2F0aW9uLnNlYXJjaCk7CiAgICBjb25zdCByZWRpcmVjdFVybCA9IHVybFBhcmFtcy5nZXQoJ3JlZGlyZWN0Jyk7CgogICAgaWYgKHJlZGlyZWN0VXJsKSB7CiAgICAgICAgbG9jYXRpb24uaHJlZiA9IHJlZGlyZWN0VXJsOwogICAgICAgIHJldHVybjsKICAgIH0KCiAgICBjb25zb2xlLmxvZygiQ3VycmVudCBXaW5kb3cgVVJMOiIsIGAke2VuY29kZVVSSUNvbXBvbmVudChsb2NhdGlvbi5ocmVmKX1gKTsKCiAgICBjb25zdCBhbGxvd2VkRG9tYWlucyA9IFsKICAgICAgICAibGlua3ZlcnRpc2UuY29tIiwgImxvb3RsYWJzLmdnIiwgImxvb3RsaW5rcy5jb20iLCAibG9vdC1saW5rLmNvbSIsICJsb290ZGVzdC5vcmciLCJsb290ZGVzdC5jb20iLCJsb290ZGVzdC5pbmZvIiwibG9vdC1saW5rcy5jb20iLCJsb290bGluay5vcmciLCJsb290bGlua3MuY28iLCAibGlua3Nsb290Lm5ldCIsICJsaW5rcy1sb290LmNvbSIsCiAgICAgICAgInBhc3Rlci5zbyIsICJwYXN0ZXIuZ2ciLCAid29yay5pbmsiLCAiY3V0eS5pbyIsICJjZXR5LmlvIiwKICAgICAgICAiYm9vc3QuaW5rIiwgImFkZm9jLnVzIiwgIm1lbmRhdGlvbmZvcmMuaW5mbyIsICJyZWtvbmlzZS5jb20iLAogICAgICAgICJtYm9vc3QubWUiLCAiYnN0LmdnIiwgImJvb28uc3QiLCAic29jaWFsLXVubG9jay5jb20iLAogICAgICAgICJzb2NpYWx3b2x2ZXouY29tIiwgInN1YjJnZXQuY29tIiwgInN1YjJ1bmxvY2suY29tIiwgInN1YjJ1bmxvY2submV0IiwKICAgICAgICAic3ViNHVubG9jay5pbyIsICJzdWJmaW5hbC5jb20iLCAidW5sb2Nrbm93Lm5ldCIsICJ5dHN1Ym1lLmNvbSIsCiAgICAgICAgImp1c3RwYXN0ZS5pdCIsICJwYXN0ZS1kcm9wLmNvbSIsICJwYXN0ZWJpbi5jb20iLCAicGFzdGVjYW55b24uY29tIiwKICAgICAgICAicGFzdGVoaWxsLmNvbSIsICJwYXN0ZW1vZGUuY29tIiwgInJlbnRyeS5vcmciLCAiYml0Lmx5IiwgImNsLmd5IiwKICAgICAgICAiZ29vLmdsIiwgImlzLmdkIiwgInJlYnJhbmQubHkiLCAicmtucy5saW5rIiwgInNob3J0ZXIubWUiLCAidC5jbyIsCiAgICAgICAgInQubHkiLCAidGlueS5jYyIsICJ0aW55bGluay5vbmwiLCAidGlueXVybC5jb20iLCAidi5nZCIKICAgIF07CgogICAgY29uc3QgaXNBbGxvd2VkID0gYWxsb3dlZERvbWFpbnMuc29tZShkb21haW4gPT4gbG9jYXRpb24uaHJlZi5pbmNsdWRlcyhkb21haW4pKTsKCiAgICBpZiAoIWlzQWxsb3dlZCkgewogICAgICAgIGNvbnNvbGUubG9nKCJVUkwgYnVrYW4gZGFyaSBzaXR1cyB5YW5nIGRpZHVrdW5nLiIpOwogICAgICAgIGRvY3VtZW50LmJvZHkuaW5uZXJIVE1MID0gYDxoMT5FcnJvcjwvaDE+PHA+SGFueWEgVVJMIGRhcmkgc2l0dXMgeWFuZyBkaWR1a3VuZyB5YW5nIGJpc2EgZGlwcm9zZXMuPC9wPmA7CiAgICAgICAgcmV0dXJuOwogICAgfQoKICAgIHRyeSB7CiAgICAgICAgY29uc3QgYXBpVXJsID0gImh0dHBzOi8vYXBpLmJ5cGFzcy53ZWIuaWQvYXBpL3VzZXJzY2lwcnQiOwogICAgICAgIGNvbnN0IHJlcXVlc3REYXRhID0gewogICAgICAgICAgICBtZXRob2Q6ICJhbnlyZXEiLAogICAgICAgICAgICBhcGlLZXk6IGFwaUtleSwKICAgICAgICAgICAgdXJsOiBlbmNvZGVVUklDb21wb25lbnQobG9jYXRpb24uaHJlZikKICAgICAgICB9OwoKICAgICAgICBjb25zdCByZXNwb25zZSA9IGF3YWl0IGZldGNoKGFwaVVybCwgewogICAgICAgICAgICBtZXRob2Q6ICJQT1NUIiwKICAgICAgICAgICAgaGVhZGVyczogewogICAgICAgICAgICAgICAgIkNvbnRlbnQtVHlwZSI6ICJhcHBsaWNhdGlvbi9qc29uIgogICAgICAgICAgICB9LAogICAgICAgICAgICBib2R5OiBKU09OLnN0cmluZ2lmeShyZXF1ZXN0RGF0YSkKICAgICAgICB9KTsKCiAgICAgICAgY29uc3QgYXBpRGF0YSA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKTsKICAgICAgICBjb25zb2xlLmxvZygiQVBJIFJlc3BvbnNlOiIsIGFwaURhdGEpOwoKICAgICAgICBpZiAoYXBpRGF0YS50YXNrSWQpIHsKICAgICAgICAgICAgY29uc29sZS5sb2coIlRhc2sgSUQgZGl0ZW11a2FuOiIsIGFwaURhdGEudGFza0lkKTsKICAgICAgICAgICAgbGV0IHN0YXR1c0RhdGE7CiAgICAgICAgICAgIGxldCByZXRyaWVzID0gMDsKICAgICAgICAgICAgY29uc3QgbWF4UmV0cmllcyA9IDk5OTk5OTk5OwoKICAgICAgICAgICAgZG8gewogICAgICAgICAgICAgICAgY29uc3Qgc3RhdHVzVXJsID0gYGh0dHBzOi8vYXBpLmJ5cGFzcy53ZWIuaWQvYXBpL2J5cGFzcy11c2VyL3N0YXR1cz90YXNrSWQ9JHthcGlEYXRhLnRhc2tJZH1gOwogICAgICAgICAgICAgICAgY29uc29sZS5sb2coIlN0YXR1cyBBUEkgUmVxdWVzdCBVUkw6Iiwgc3RhdHVzVXJsKTsKICAgICAgICAgICAgICAgIGNvbnN0IHN0YXR1c1Jlc3BvbnNlID0gYXdhaXQgZmV0Y2goc3RhdHVzVXJsLCB7IG1ldGhvZDogJ0dFVCcgfSk7CiAgICAgICAgICAgICAgICBzdGF0dXNEYXRhID0gYXdhaXQgc3RhdHVzUmVzcG9uc2UuanNvbigpOwogICAgICAgICAgICAgICAgY29uc29sZS5sb2coIlN0YXR1cyBBUEkgUmVzcG9uc2UgRGF0YToiLCBzdGF0dXNEYXRhKTsKCiAgICAgICAgICAgICAgICBpZiAoc3RhdHVzRGF0YS5zdGF0dXMgPT09ICJwcm9jZXNzaW5nIikgewogICAgICAgICAgICAgICAgICAgIGNvbnNvbGUubG9nKCJTdGF0dXMgbWFzaWggcHJvY2Vzc2luZywgbWVuY29iYSBsYWdpLi4uIik7CiAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICByZXRyaWVzKys7CiAgICAgICAgICAgICAgICBpZiAocmV0cmllcyA+PSBtYXhSZXRyaWVzKSB7CiAgICAgICAgICAgICAgICAgICAgY29uc29sZS5sb2coIk1heCByZXRyaWVzIHJlYWNoZWQsIGV4aXRpbmcuLi4iKTsKICAgICAgICAgICAgICAgICAgICBicmVhazsKICAgICAgICAgICAgICAgIH0KCiAgICAgICAgICAgIH0gd2hpbGUgKHN0YXR1c0RhdGEuc3RhdHVzID09PSAicHJvY2Vzc2luZyIpOwoKICAgICAgICAgICAgaWYgKHN0YXR1c0RhdGEuc3RhdHVzID09PSAnY29tcGxldGVkJykgewogICAgICAgICAgICAgICAgY29uc29sZS5sb2coIlVSTCBCeXBhc3MgYmVyaGFzaWw6Iiwgc3RhdHVzRGF0YS5yZXN1bHQpOwogICAgICAgICAgICAgICAgYXdhaXQgZGVsYXkoY291bnREZWxheSk7CiAgICAgICAgICAgICAgICBsb2NhdGlvbi5ocmVmID0gc3RhdHVzRGF0YS5yZXN1bHQ7CiAgICAgICAgICAgICAgICByZXR1cm47CiAgICAgICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgICAgICBjb25zb2xlLmxvZygiQnlwYXNzIGdhZ2FsOiIsIHN0YXR1c0RhdGEubWVzc2FnZSB8fCAiVW5rbm93biBlcnJvci4iKTsKICAgICAgICAgICAgICAgIGRvY3VtZW50LmJvZHkuaW5uZXJIVE1MID0gYDxoMT5SZWRpcmVjdCBGYWlsZWQ8L2gxPjxwPiR7c3RhdHVzRGF0YS5tZXNzYWdlIHx8ICJVbmtub3duIGVycm9yLiJ9PC9wPmA7CiAgICAgICAgICAgIH0KICAgICAgICB9IGVsc2UgewogICAgICAgICAgICBjb25zb2xlLmxvZygiVGFzayBJRCB0aWRhayBkaXRlbXVrYW4gZGkgQVBJIFJlc3BvbnNlLiIpOwogICAgICAgICAgICBkb2N1bWVudC5ib2R5LmlubmVySFRNTCA9IGA8aDE+QVBJIEVycm9yPC9oMT48cD5UYXNrIElEIHRpZGFrIGRpdGVtdWthbi48L3A+YDsKICAgICAgICB9CiAgICB9IGNhdGNoIChlcnJvcikgewogICAgICAgIGNvbnNvbGUuZXJyb3IoIkVycm9yOiIsIGVycm9yKTsKICAgICAgICBkb2N1bWVudC5ib2R5LmlubmVySFRNTCA9IGA8aDE+RXJyb3I8L2gxPjxwPiR7ZXJyb3IubWVzc2FnZX08L3A+YDsKICAgIH0KfSkoKTs=','450528GIszmw','24VhyxpF','BrhSW','9xuHyBv','471400prkTcf','75063RJuqEW','1283877dvvFRB'];_0x4e15=function(){return _0x2ee253;};return _0x4e15();}
