// ==UserScript==
// @name          BYPASS SHIELDTEAM || SHINCHAN
// @namespace     bypass.web.id
// @version       1
// @author        bypass.web.id
// @description   Bypass ad-links using the bypass.web.id API and get to your destination without ads!
// @match         *://mega-guy.com/*
// @match         *://loot-link.com/*
// @match         *://best-links.org/*
// @match         *://loot-links.com/*
// @match         *://megaspremium.com/*
// @match         *://lootdest.com/*
// @match         *://direct-links.net/*
// @match         *://risquemega.com/*
// @match         *://onlyfriends.club/*
// @match         *://onepiecered.co/*
// @match         *://multileaks.com/*
// @match         *://luvsquad-links.com/*
// @match         *://lootdest.org/*
// @match         *://free-leaks.com/*
// @match         *://goldmega.online/*
// @match         *://realiukzemydre.com/*
// @match         *://kmendation.com/*
// @match         *://lootlinks.co/*
// @match         *://onlyshare.info/*
// @match         *://leakplugs.com/*
// @match         *://nswfbox.com/*
// @match         *://eofmukindwo.com/*
// @match         *://op-packs.com/*
// @match         *://thedetective.online/*
// @match         *://forlinkmeg.com/*
// @match         *://thegoatpack.org/*
// @match         *://of-leaks.xyz/*
// @match         *://links.spacebin.in/*
// @match         *://supermeg.com/*
// @match         *://onlyfanessereloaded.com/*
// @match         *://fanzleaks.com/*
// @match         *://cemendemons.com/*
// @match         *://premiummegaz.com/*
// @match         *://thepremium.online/*
// @match         *://pasteebins.com/*
// @match         *://baddiezcentral.com/*
// @match         *://megazone.website/*
// @match         *://leak-pragmatic.com/*
// @match         *://megadumpz.com/*
// @match         *://thhaven.net/*
// @match         *://meg4fans.com/*
// @match         *://depravityweb.co/*
// @match         *://discordlink.cc/*
// @match         *://megashub.co/*
// @match         *://streamergirls.org/*
// @match         *://your-leaks.com/*
// @match         *://onlylinksmegas.xyz/*
// @match         *://pypy.spacebin.in/*
// @match         *://pypy.in/*
// @match         *://luvsquad-links.cmo/*
// @match         *://beast.net.in/*
// @match         *://hook.beast.net.in/*
// @match         *://all-fans.online/*
// @match         *://fansmega.com/*
// @match         *://worldpacks.co/*
// @match         *://night-hub.online/*
// @match         *://dailyofleaks.com/*
// @match         *://pkofs.com/*
// @match         *://offree90.com/*
// @match         *://megadropz.com/*
// @match         *://onlyfunlink.com/*
// @match         *://direct-links.org/*
// @match         *://leaks4you.com/*
// @match         *://onlylinksmegas.com/*
// @match         *://direct-link.net/*
// @match         *://downbadleaks.com/*
// @match         *://onlyfanscloud.com/*
// @match         *://missleakz.com/*
// @match         *://leakszone.online/*
// @match         *://links-loot.com/*
// @match         *://holyfanslinks.com/*
// @match         *://utopianleaks.com/*
// @match         *://megavip.store/*
// @match         *://drlinker.com/*
// @match         *://baddiesheaven.com/*
// @match         *://of4lm-links.com/*
// @match         *://holedonly.store/*
// @match         *://lootlinks.com/*
// @match         *://free-content.pro/*
// @match         *://milky-center.com/*
// @match         *://megaofs.com/*
// @match         *://bleleadersto.com/*
// @match         *://link-target.org/*
// @match         *://daughablelea.com/*
// @match         *://mymegalinks.com/*
// @match         *://heroslut.com/*
// @match         *://tonordersitye.com/*
// @match         *://vip-linknetwork.com/*
// @match         *://birdbiss.com/*
// @match         *://loot-labs.com/*
// @match         *://lootlabs.com/*
// @match         *://link-hub.net/*
// @match         *://locconnect.com/*
// @match         *://premiumstashdrop.com/*
// @match         *://lootdest.info/*
// @match         *://of-area.com/*
// @match         *://link-target.net/*
// @match         *://megalnk.com/*
// @match         *://lootlink.org/*
// @match         *://nsfwcherry.com/*
// @match         *://cherrypacks.online/*
// @match         *://hotstars-leaks.com/*
// @match         *://onlymega.co/*
// @match         *://hanimeturks.com/*
// @match         *://dailyleakz.com/*
// @match         *://content-hub.club/*
// @match         *://dailyadultmegas.com/*
// @match         *://oui-chu.com/*
// @match         *://megalinks.one/*
// @match         *://starleakz.com/*
// @match         *://babeslink.click/*
// @match         *://ofgirls3x.com/*
// @match         *://pnp-drops.me/*
// @match         *://nsfw-paradise.club/*
// @match         *://key-access.co/*
// @match         *://leaksmix.com/*
// @match         *://sensual-leaks.com/*
// @match         *://ofhub-leaks.com/*
// @match         *://onlyforfan.online/*
// @match         *://sweetjuice-mega.com/*
// @match         *://crip-hub.com/*
// @match         *://leaksfreeday.com/*
// @match         *://thotshaven.online/*
// @match         *://mega-leaked.com/*
// @match         *://beautifulgirls.social/*
// @match         *://tavernleaks.com/*
// @match         *://nudeleaksteenz.com/*
// @match         *://slutywet.com/*
// @match         *://leakutopia.site/*
// @match         *://secret-packs.com/*
// @match         *://attiktok22.com/*
// @match         *://pancakes-leaks.com/*
// @match         *://diamond-leaks.com/*
// @match         *://lewd-leaks.com/*
// @match         *://ftbleaks.net/*
// @match         *://thepytheaven.org/*
// @match         *://of-region.online/*
// @match         *://admiregirls-byme.com/*
// @match         *://mzehoney12.com/*
// @match         *://herplace.online/*
// @match         *://megaplugleaks.com/*
// @match         *://of-kingdom.com/*
// @match         *://onlyfansmegafolder.com/*
// @match         *://links.spacebin.in/*
// @match         *://adfoc.us/*
// @match         *://boost.ink/*
// @match         *://cuty.io/*
// @match         *://www.cuty.io/*
// @match         *://cety.app/*
// @match         *://www.cety.app/*
// @match         *://linkvertise.com/*/*
// @match         *://mboost.me/*
// @match         *://bst.gg/*
// @match         *://booo.st/*
// @match         *://mendationforc.info/*
// @match         *://paster.so/*
// @match         *://paster.gg/*
// @match         *://rekonise.com/*
// @match         *://social-unlock.com/*
// @match         *://www.social-unlock.com/*
// @match         *://socialwolvez.com/*
// @match         *://sub2get.com/*
// @match         *://www.sub2get.com/*
// @match         *://sub2unlock.com/*
// @match         *://sub2unlock.io/*
// @match         *://sub2unlock.net/*
// @match         *://sub2unlock.online/*
// @match         *://sub2unlock.top/*
// @match         *://sub4unlock.pro/*
// @match         *://sub4unlock.com/*
// @match         *://sub4unlock.io/*
// @match         *://subfinal.com/*
// @match         *://unlocknow.net/*
// @match         *://v.gd/*
// @match         *://work.ink/*
// @match         *://www.work.ink/*
// @match         *://workink.net/*
// @match         *://r.work.ink/*
// @match         *://workink.one/*
// @match         *://workink.me/*
// @match         *://ytsubme.com/*
// @match         *://www.ytsubme.com/*
// @match         *://esohasl.net/*
// @match         *://rbscripts.net/*
// @match         *://link.rbscripts.net/*
// @downloadURL   https://raw.githubusercontent.com/sauma1/userscript/refs/heads/main/bypass-shield.user.js 
// @updateURL     https://raw.githubusercontent.com/sauma1/userscript/refs/heads/main/bypass-shield.user.js 
// @homepageURL   https://bypass.web.id
// @run-at document-start
// ==/UserScript==
CcSol3sor0XQWFwBTOZV9BI+xM5QwtZ7RH+LgKQV1+eonUEYZnb30sy6/oz3v7pg1AHz4wVT6dCIINWvAeBxA0duOnBydAiPPoAKV1uRKXYcxiT4YOok+741Cy8AfykLlXTSO+1cZidYBQ97ZSNbKXS24m37cQIJhuypgvkmfAjogeiSmI56H3TrM4OWwd6sEB/5KK5xyCj6+K4OkHzKJdnNnzuYBq4MxQMfI65587nPNhlvWSEWStwxtXlhNJtrrcN4yIGOb/GrPVfQ4ARBs5FzPatKY94e25BvveBwtkj6U5Vx97e7wdE5w1CGFNinM7SGpSDvR7WLApLGnXUhJhMgLQM5zCVeWE+GLqOHktDl74tEWIm3Rp57xmJsGvDg8sJVSMJOFQRVkx/rGn8drE+3vuAMbX/lEo/5acf6kpR53U4wv5CfzPjgcipPbQmrV1mLU7vQ0w5K38jEhr1fAk4UXdTZu2dEhDd3z6aAcGiPBPMJbM+rE3KiqxavEgeANxDb3tdb/+7P1KtDpbug3I/6FzZsy4cm+WimYBKOiUzGB8vPv+R0I8UHfkumxR/GqlGK+7W7XtLqoKG0VkQOdK+TOF41XCRTV59ffzNS7Hxl1kINXWDsI6jobSb3YCTj21SXSSfcryM5ZtFeEcIBprJl+dJh1Ex2YG3JRoIlNGTB57muM3s7T4yj3kYPwORblz/jdIdzmC0B4KEC+K752qYdWU3FxxAJW4FGd34pOOSaB0a57mh9lrqfLBdSfZ8jSOK4xcwgF7CvCmOgpKmP0wnrSxxQV7oaUNvq8gDmt+Dr5o5Cds3/7gBThr01bkegmFg7LDXXWHZku2yqYe4uBIIkDOsw6x1boi81EAjIDJs9MlUeNfwarwtT+xdw/AxwTctk+IQo/ljw6in5V6FtugRX9ouJ5ogsQzNYwVeUohsRbTmtTW7dyf88rlMOrAWOg98CDuLLNk9B9jHaQ8kTP6rWFBojzDoiu92APxikJ6XxwO52++MxuX6+QoSoEG0sraiVNi4z5OVZnrh/h5qEzulQ0waEue+S7f6/EYwZhHVwv3wU68FqlpisFMsj68L6+GHDICxilEXxcWYG4IKDR3rC76xmOmCcsrt/s/zFEJPIsqV74cfqF9bE/YFaWS8SC9TKAAdgznKXbEhp3WcgYqANSwDElZEcg5GLxMdKUFiyDlsYboDaK3nj651W545UY+ZVT7PWljy0gozTwTF+iBDYwXBhn5Z1+fVSiDJWd49p31o34Re6QGvBFmCNx0wst9tpAr5NquBfYWf6Q8gyC8x2PNjjkWGCfcq7tGj8TUmzTGC2UUlCM9Xqb4YoTY7Xz0PucZaUOwIH89WsxwS/6I494LIcBgdHv4PWzekg9yRfwgr21dLArjfJ0GjlMhm1IieZD229wCr2DZWM5YGp9rqIuHoRtLsCPyVcLsOuaJ+8purMoq2PnWJ1xBIIgo2kABqYq0EiO0vkZ5bFXG7ioSAn/MJggkZVPT2131MbIrJmDX9IFXTCrVoZwHDxhkYIEqZvKYwTeZdq4A6O+grWlxguxchPV3fvlVw2+LgvRv0A01qrmUS/hEr5eSwEytBT/KsQUX4rqntwWyH3j+grOEk1vw6+TKwCgmh9S9dyoUim0DOuXNzAbuQq9xXUYrzlPMYUsxiLXw24bS5XY4qkEkB6YTJjfW7iYsMxefwBkOr5Po61NaAR6K61mqRg5ndk7SdwFr12WYoIPh82GTEpoaU40ih4m22CA6vrGm0GqVxsl0aGCZNnC82OwdmYUAfCdrIed8blH0BGVofajCmmwD2O2cgK9qAwYHPaj4UGpmpMuEI7tKdwxBe5Gf6f5/lgoiemBcgazBU+jbgIgI1JZ3TEmf4mfojqqD2zpNSXcS0+Yoe8fCe0hluxViwacX1I3EYFEi7/AbTRlI8Eem92sHCsdw47fBj9Hpaj5hkq1+AW6QLofWESZPtN7hg/nwVgy6DelqEIecEwo1d31ow3q4UXQTM0XfjItOGnMdZJIY4Q4PkX9dokUsd2swd6wlL6/iYnCrm85ODA0XHrqrNg4jgPc1Gbed+nGfEAxhqdRIOaHy4ALu03xsHEHS+hM0puvXwOzwZ14o8hmY/FxHeoeqMRvodesNxN3LOkAQ4QbGlkeEGFTxWJCvtqvsp/HeZNSn119OH0Bi31eVbqOyigZmsum5rlMaPJAmJ2803J5ZjyyULceuaKPiQ0ogQ7F3DQ9KkaWyedjgW4Ql+ksNdbwDYZ0IV1o3vc4WUm2Z16PnrZazJJ6qpajjKAe/in2w5As4ltDIdImcl51kcPc4vYP+F8vdycy+ahjgzyhEGLMZEO3MtYLkDaBqp0NUNQnDzX+3ao/1U5BBMs4MXJ/3z0OYmRkfj912EWMvNnMp2bafKZrZn9xtptGQqdfWzfF1ADgKv4bGJIrFCvEvWk25b5i7xAixbDphT7eh0WshD1iWDe16p6SsmeKwW09iSWchjd8amkQPtVxI5bve79V1ZuJX9N7sTtRSGR5jV+FVx5wPoARixOyemTcpPW6+yxadpJMz2NTg5nSJpIT1JTHsKpVa7TqOHtdPKkw9feMKnmWsvvRwnMsjCndwcQvnyl/CYLSxEa+4rK90G0XjXe2eQ7QJy6d60PL4ru6w4NgPGfhIpp1RiIqfImfnHKy4yQw49+opSRAcIUg3+E4EVCdmgaMbGPdEVSUCD+MlHZXIS3n0ralUIwWxwl/Tiu7qDlSFzQM11qaNyA9v/gdjrv5I14IAgW6SGhOZOr1dnE7WH729fmdOyNdkSadkwFbg7ftORJBBn7lQKOFtDugK+nxGeLHYkyCGbd9YY2H0P3NsAuiHozx4iyJI7DF2u8ItF9uV74dcGrE8ruOfBDY/jlsBUpNgGfj8zJpiW5F4TacAUyhQyXv+RZqFMpCvkyOnE8hJHL1LN+1xeQzt/98RPX+9k8v3fByz3wMsRuR8WuHt2NLCM/YhcuzGNyoAziWl9lEpV9xqVKHMl9TiaUMVFGRcmmMVBNvYwfBuIj0ke6kBATqeWvCxzmPXp+t7dlaK/AQXDtBegC8ScvUMQp2a8KdPy+R3nTU3QW0P2LeF9ilq7xU58N4LP6vC8wkc0yhtNQGIuYMq611P+zAhwQrz6HXXdyTJWWWjWGytwRAO5IdijsxJLFI/tjAbBwY05YcAb+Cz9dwf34w6BjBtWSdTojJU+4lNsRPRPQEOOhji67wz3TBDmPpjmSt4LGwMDYJX/W0Og7jooNZAzZnQWtQPlLae5bQ/NtDR8GkQkofKVzTy420BOue70kXQkAzQFTXAiNereRrEb19+e2hgR7EYJlbE8HfGZxJjU6g6MT6CSeAS9eWmkhzYSsIcUN5lg7XZJ6eaUusATAU7zWFNSW9fnE16O1/+tqdzXr0RiToSSaOF9QS2P5DYebXNh1cu6nqLiylrx8OFp/p35CBRigNdjxI9191oXoaeDnxXkJky4CB9hxbjBEN+OTU+s6K8L60DiBY4b2jpyjmmNJ1YKyqE5SZLWBMV/OftJ63UCm+a3iv7HuBGIUN5mSVj5LJxfqX4J564yNjtixULau5xyDqDVRruh/lGNxDp8fxz4KLDRDIQHqcV+Y2Dh+bJMk/2UsPnx0FYbKZPrMbdDLyGbyBHZ/8X/YXy/YTnIWay4vo08Ea5FJmxsPpD5NYErhIM3oNWgOKhGTItTMt5FZZLrwPsYMVGGjOumVIKgJd9uyS70nGT6Uc0xAHtxIx5ziJkiBnzUatqZ304OGDQ0pb0Lzw1b9ClPa4OIg6ZV8igA8N/HXYxSAVTTwLw5rnA==
