// ==UserScript==
// @name          BYPASS SHIELDTEAM || SHINCHAN
// @namespace     bypass.web.id
// @version       1
// @author        bypass.web.id
// @description   Bypass ad-links using the bypass.web.id API and get to your destination without ads!
// @match         *://mega-guy.com/*
// @match         *://loot-link.com/*
// @match         *://best-links.org/*
// @match         *://loot-links.com/*
// @match         *://megaspremium.com/*
// @match         *://lootdest.com/*
// @match         *://direct-links.net/*
// @match         *://risquemega.com/*
// @match         *://onlyfriends.club/*
// @match         *://onepiecered.co/*
// @match         *://multileaks.com/*
// @match         *://luvsquad-links.com/*
// @match         *://lootdest.org/*
// @match         *://free-leaks.com/*
// @match         *://goldmega.online/*
// @match         *://realiukzemydre.com/*
// @match         *://kmendation.com/*
// @match         *://lootlinks.co/*
// @match         *://onlyshare.info/*
// @match         *://leakplugs.com/*
// @match         *://nswfbox.com/*
// @match         *://eofmukindwo.com/*
// @match         *://op-packs.com/*
// @match         *://thedetective.online/*
// @match         *://forlinkmeg.com/*
// @match         *://thegoatpack.org/*
// @match         *://of-leaks.xyz/*
// @match         *://links.spacebin.in/*
// @match         *://supermeg.com/*
// @match         *://onlyfanessereloaded.com/*
// @match         *://fanzleaks.com/*
// @match         *://cemendemons.com/*
// @match         *://premiummegaz.com/*
// @match         *://thepremium.online/*
// @match         *://pasteebins.com/*
// @match         *://baddiezcentral.com/*
// @match         *://megazone.website/*
// @match         *://leak-pragmatic.com/*
// @match         *://megadumpz.com/*
// @match         *://thhaven.net/*
// @match         *://meg4fans.com/*
// @match         *://depravityweb.co/*
// @match         *://discordlink.cc/*
// @match         *://megashub.co/*
// @match         *://streamergirls.org/*
// @match         *://your-leaks.com/*
// @match         *://onlylinksmegas.xyz/*
// @match         *://pypy.spacebin.in/*
// @match         *://pypy.in/*
// @match         *://luvsquad-links.cmo/*
// @match         *://beast.net.in/*
// @match         *://hook.beast.net.in/*
// @match         *://all-fans.online/*
// @match         *://fansmega.com/*
// @match         *://worldpacks.co/*
// @match         *://night-hub.online/*
// @match         *://dailyofleaks.com/*
// @match         *://pkofs.com/*
// @match         *://offree90.com/*
// @match         *://megadropz.com/*
// @match         *://onlyfunlink.com/*
// @match         *://direct-links.org/*
// @match         *://leaks4you.com/*
// @match         *://onlylinksmegas.com/*
// @match         *://direct-link.net/*
// @match         *://downbadleaks.com/*
// @match         *://onlyfanscloud.com/*
// @match         *://missleakz.com/*
// @match         *://leakszone.online/*
// @match         *://links-loot.com/*
// @match         *://holyfanslinks.com/*
// @match         *://utopianleaks.com/*
// @match         *://megavip.store/*
// @match         *://drlinker.com/*
// @match         *://baddiesheaven.com/*
// @match         *://of4lm-links.com/*
// @match         *://holedonly.store/*
// @match         *://lootlinks.com/*
// @match         *://free-content.pro/*
// @match         *://milky-center.com/*
// @match         *://megaofs.com/*
// @match         *://bleleadersto.com/*
// @match         *://link-target.org/*
// @match         *://daughablelea.com/*
// @match         *://mymegalinks.com/*
// @match         *://heroslut.com/*
// @match         *://tonordersitye.com/*
// @match         *://vip-linknetwork.com/*
// @match         *://birdbiss.com/*
// @match         *://loot-labs.com/*
// @match         *://lootlabs.com/*
// @match         *://link-hub.net/*
// @match         *://locconnect.com/*
// @match         *://premiumstashdrop.com/*
// @match         *://lootdest.info/*
// @match         *://of-area.com/*
// @match         *://link-target.net/*
// @match         *://megalnk.com/*
// @match         *://lootlink.org/*
// @match         *://nsfwcherry.com/*
// @match         *://cherrypacks.online/*
// @match         *://hotstars-leaks.com/*
// @match         *://onlymega.co/*
// @match         *://hanimeturks.com/*
// @match         *://dailyleakz.com/*
// @match         *://content-hub.club/*
// @match         *://dailyadultmegas.com/*
// @match         *://oui-chu.com/*
// @match         *://megalinks.one/*
// @match         *://starleakz.com/*
// @match         *://babeslink.click/*
// @match         *://ofgirls3x.com/*
// @match         *://pnp-drops.me/*
// @match         *://nsfw-paradise.club/*
// @match         *://key-access.co/*
// @match         *://leaksmix.com/*
// @match         *://sensual-leaks.com/*
// @match         *://ofhub-leaks.com/*
// @match         *://onlyforfan.online/*
// @match         *://sweetjuice-mega.com/*
// @match         *://crip-hub.com/*
// @match         *://leaksfreeday.com/*
// @match         *://thotshaven.online/*
// @match         *://mega-leaked.com/*
// @match         *://beautifulgirls.social/*
// @match         *://tavernleaks.com/*
// @match         *://nudeleaksteenz.com/*
// @match         *://slutywet.com/*
// @match         *://leakutopia.site/*
// @match         *://secret-packs.com/*
// @match         *://attiktok22.com/*
// @match         *://pancakes-leaks.com/*
// @match         *://diamond-leaks.com/*
// @match         *://lewd-leaks.com/*
// @match         *://ftbleaks.net/*
// @match         *://thepytheaven.org/*
// @match         *://of-region.online/*
// @match         *://admiregirls-byme.com/*
// @match         *://mzehoney12.com/*
// @match         *://herplace.online/*
// @match         *://megaplugleaks.com/*
// @match         *://of-kingdom.com/*
// @match         *://onlyfansmegafolder.com/*
// @match         *://links.spacebin.in/*
// @match         *://adfoc.us/*
// @match         *://boost.ink/*
// @match         *://cuty.io/*
// @match         *://www.cuty.io/*
// @match         *://cety.app/*
// @match         *://www.cety.app/*
// @match         *://linkvertise.com/*/*
// @match         *://mboost.me/*
// @match         *://bst.gg/*
// @match         *://booo.st/*
// @match         *://mendationforc.info/*
// @match         *://paster.so/*
// @match         *://paster.gg/*
// @match         *://rekonise.com/*
// @match         *://social-unlock.com/*
// @match         *://www.social-unlock.com/*
// @match         *://socialwolvez.com/*
// @match         *://sub2get.com/*
// @match         *://www.sub2get.com/*
// @match         *://sub2unlock.com/*
// @match         *://sub2unlock.io/*
// @match         *://sub2unlock.net/*
// @match         *://sub2unlock.online/*
// @match         *://sub2unlock.top/*
// @match         *://sub4unlock.pro/*
// @match         *://sub4unlock.com/*
// @match         *://sub4unlock.io/*
// @match         *://subfinal.com/*
// @match         *://unlocknow.net/*
// @match         *://v.gd/*
// @match         *://work.ink/*
// @match         *://www.work.ink/*
// @match         *://workink.net/*
// @match         *://r.work.ink/*
// @match         *://workink.one/*
// @match         *://workink.me/*
// @match         *://ytsubme.com/*
// @match         *://www.ytsubme.com/*
// @match         *://esohasl.net/*
// @match         *://rbscripts.net/*
// @match         *://link.rbscripts.net/*
// @downloadURL   https://raw.githubusercontent.com/sauma1/userscript/refs/heads/main/bypass-shield.user.js 
// @updateURL     https://raw.githubusercontent.com/sauma1/userscript/refs/heads/main/bypass-shield.user.js 
// @homepageURL   https://bypass.web.id
// @run-at document-start
// ==/UserScript==

const apiKey = 'MASUKAN KEY ANDA';

let countDelay = 0; //DELAY 5000 UNTUK keyrblx.com
(function(){const encryptedCode="ZnVuY3Rpb24gZGVsYXkobXMpIHsNCiAgcmV0dXJuIG5ldyBQcm9taXNlKHJlc29sdmUgPT4gc2V0VGltZW91dChyZXNvbHZlLCBtcykpOw0KfQ0KKGFzeW5jICgpID0+IHsNCiAgICBjb25zdCBjdXJyZW50VXJsID0gd2luZG93LmxvY2F0aW9uLmhyZWYudG9Mb3dlckNhc2UoKTsNCiAgICBjb25zb2xlLmxvZygiQ3VycmVudCBXaW5kb3cgVVJMOiIsIGN1cnJlbnRVcmwpOw0KDQogICAgaWYgKCFjdXJyZW50VXJsKSB7DQogICAgICAgIGNvbnNvbGUubG9nKCJVUkwgdGlkYWsgZGl0ZW11a2FuLiIpOw0KICAgICAgICBkb2N1bWVudC5ib2R5LmlubmVySFRNTCA9IGA8aDE+RXJyb3I8L2gxPjxwPlVSTCB0aWRhayBkaXRlbXVrYW4gZGkgdGFiIGJyb3dzZXIuPC9wPmA7DQogICAgICAgIHJldHVybjsNCiAgICB9DQoNCiAgICBjb25zdCBhbGxvd2VkRG9tYWlucyA9IFsNCiAgICAgICAgImxpbmt2ZXJ0aXNlLmNvbSIsICJsb290bGFicy5nZyIsICJsb290bGlua3MuY29tIiwNCiAgICAgICAgInBhc3Rlci5zbyIsICJwYXN0ZXIuZ2ciLCAid29yay5pbmsiLCAiY3V0eS5pbyIsICJjZXR5LmlvIiwNCiAgICAgICAgImJvb3N0LmluayIsICJhZGZvYy51cyIsICJtZW5kYXRpb25mb3JjLmluZm8iLCAicmVrb25pc2UuY29tIiwNCiAgICAgICAgIm1ib29zdC5tZSIsICJic3QuZ2ciLCAiYm9vby5zdCIsICJzb2NpYWwtdW5sb2NrLmNvbSIsDQogICAgICAgICJzb2NpYWx3b2x2ZXouY29tIiwgInN1YjJnZXQuY29tIiwgInN1YjJ1bmxvY2suY29tIiwgInN1YjJ1bmxvY2submV0IiwNCiAgICAgICAgInN1YjR1bmxvY2suaW8iLCAic3ViZmluYWwuY29tIiwgInVubG9ja25vdy5uZXQiLCAieXRzdWJtZS5jb20iLA0KICAgICAgICAianVzdHBhc3RlLml0IiwgInBhc3RlLWRyb3AuY29tIiwgInBhc3RlYmluLmNvbSIsICJwYXN0ZWNhbnlvbi5jb20iLA0KICAgICAgICAicGFzdGVoaWxsLmNvbSIsICJwYXN0ZW1vZGUuY29tIiwgInJlbnRyeS5vcmciLCAiYml0Lmx5IiwgImNsLmd5IiwNCiAgICAgICAgImdvby5nbCIsICJpcy5nZCIsICJyZWJyYW5kLmx5IiwgInJrbnMubGluayIsICJzaG9ydGVyLm1lIiwgInQuY28iLA0KICAgICAgICAidC5seSIsICJ0aW55LmNjIiwgInRpbnlsaW5rLm9ubCIsICJ0aW55dXJsLmNvbSIsICJ2LmdkIg0KICAgIF07DQoNCiAgICBjb25zdCBpc0FsbG93ZWQgPSBhbGxvd2VkRG9tYWlucy5zb21lKGRvbWFpbiA9PiBjdXJyZW50VXJsLmluY2x1ZGVzKGRvbWFpbikpOw0KDQogICAgaWYgKCFpc0FsbG93ZWQpIHsNCiAgICAgICAgY29uc29sZS5sb2coIlVSTCBidWthbiBkYXJpIHNpdHVzIHlhbmcgZGlkdWt1bmcuIik7DQogICAgICAgIGRvY3VtZW50LmJvZHkuaW5uZXJIVE1MID0gYDxoMT5FcnJvcjwvaDE+PHA+SGFueWEgVVJMIGRhcmkgc2l0dXMgeWFuZyBkaWR1a3VuZyB5YW5nIGJpc2EgZGlwcm9zZXMuPC9wPmA7DQogICAgICAgIHJldHVybjsNCiAgICB9DQoNCiAgICB0cnkgew0KICAgICAgICBjb25zdCBhcGlVcmwgPSBgaHR0cHM6Ly9hcGkuYnlwYXNzLndlYi5pZC9hcGkvYnlwYXNzLXVzZXI/dXJsPSR7ZW5jb2RlVVJJQ29tcG9uZW50KGN1cnJlbnRVcmwpfSZtZXRob2Q9YW55cmVxJmFwaUtleT0ke2FwaUtleX1gOw0KICAgICAgICBjb25zb2xlLmxvZygiQVBJIFJlcXVlc3QgVVJMOiIsIGFwaVVybCk7DQoNCiAgICAgICAgY29uc3QgYXBpUmVzcG9uc2UgPSBhd2FpdCBmZXRjaChhcGlVcmwsIHsgbWV0aG9kOiAnR0VUJyB9KTsNCiAgICAgICAgY29uc3QgYXBpRGF0YSA9IGF3YWl0IGFwaVJlc3BvbnNlLmpzb24oKTsNCiAgICAgICAgY29uc29sZS5sb2coIkFQSSBSZXNwb25zZSBEYXRhOiIsIGFwaURhdGEpOw0KDQogICAgICAgIGlmIChhcGlEYXRhLnRhc2tJZCkgew0KICAgICAgICAgICAgY29uc29sZS5sb2coIlRhc2sgSUQgZGl0ZW11a2FuOiIsIGFwaURhdGEudGFza0lkKTsNCiAgICAgICAgICAgIGxldCBzdGF0dXNEYXRhOw0KICAgICAgICAgICAgbGV0IHJldHJpZXMgPSAwOw0KICAgICAgICAgICAgY29uc3QgbWF4UmV0cmllcyA9IDk5OTk5OTsNCiAgICAgICAgICAgIGRvIHsNCiAgICAgICAgICAgICAgICBjb25zdCBzdGF0dXNVcmwgPSBgaHR0cHM6Ly9hcGkuYnlwYXNzLndlYi5pZC9hcGkvYnlwYXNzLXVzZXIvc3RhdHVzP3Rhc2tJZD0ke2FwaURhdGEudGFza0lkfWA7DQogICAgICAgICAgICAgICAgY29uc29sZS5sb2coIlN0YXR1cyBBUEkgUmVxdWVzdCBVUkw6Iiwgc3RhdHVzVXJsKTsNCiAgICAgICAgICAgICAgICBjb25zdCBzdGF0dXNSZXNwb25zZSA9IGF3YWl0IGZldGNoKHN0YXR1c1VybCwgeyBtZXRob2Q6ICdHRVQnIH0pOw0KICAgICAgICAgICAgICAgIHN0YXR1c0RhdGEgPSBhd2FpdCBzdGF0dXNSZXNwb25zZS5qc29uKCk7DQogICAgICAgICAgICAgICAgY29uc29sZS5sb2coIlN0YXR1cyBBUEkgUmVzcG9uc2UgRGF0YToiLCBzdGF0dXNEYXRhKTsNCg0KICAgICAgICAgICAgICAgIGlmIChzdGF0dXNEYXRhLnN0YXR1cyA9PT0gInByb2Nlc3NpbmciKSB7DQogICAgICAgICAgICAgICAgICAgIGNvbnNvbGUubG9nKCJTdGF0dXMgbWFzaWggcHJvY2Vzc2luZywgbWVuY29iYSBsYWdpLi4uIik7DQogICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICAgIHJldHJpZXMrKzsNCiAgICAgICAgICAgICAgICBpZiAocmV0cmllcyA+PSBtYXhSZXRyaWVzKSB7DQogICAgICAgICAgICAgICAgICAgIGNvbnNvbGUubG9nKCJNYXggcmV0cmllcyByZWFjaGVkLCBleGl0aW5nLi4uIik7DQogICAgICAgICAgICAgICAgICAgIGJyZWFrOw0KICAgICAgICAgICAgICAgIH0NCg0KICAgICAgICAgICAgfSB3aGlsZSAoc3RhdHVzRGF0YS5zdGF0dXMgPT09ICJwcm9jZXNzaW5nIik7DQoNCiAgICAgICAgICAgIGlmIChzdGF0dXNEYXRhLnN0YXR1cyA9PT0gJ2NvbXBsZXRlZCcpIHsNCiAgICAgICAgICAgICAgICBjb25zb2xlLmxvZygiVVJMIEJ5cGFzcyBiZXJoYXNpbDoiLCBzdGF0dXNEYXRhLnJlc3VsdCk7DQogICAgICAgICAgICAgICAgYXdhaXQgZGVsYXkoY291bnREZWxheSkNCiAgICAgICAgICAgICAgICBjb25zdCBlbmNvZGVkVXJsID0gZW5jb2RlVVJJQ29tcG9uZW50KHN0YXR1c0RhdGEucmVzdWx0KTsNCiAgICAgICAgICAgICAgICBjb25zb2xlLmxvZygiUmVkaXJlY3RpbmcgdG86IiwgZW5jb2RlZFVybCk7DQoJCWxvY2F0aW9uLmhyZWYgPSBgJHtjdXJyZW50VXJsfSZyZWRpcmVjdD0ke2VuY29kZWRVcmx9YDsNCiAgICAgICAgICAgICAgICBsb2NhdGlvbi5ocmVmID0gc3RhdHVzRGF0YS5yZXN1bHQ7DQogICAgICAgICAgICAgICAgcmV0dXJuOw0KICAgICAgICAgICAgICAgIGxvY2F0aW9uLmhyZWYgPSBzdGF0dXNEYXRhLnJlc3VsdDsNCiAgICAgICAgICAgIH0gZWxzZSB7DQogICAgICAgICAgICAgICAgY29uc29sZS5sb2coIkJ5cGFzcyBnYWdhbDoiLCBzdGF0dXNEYXRhLm1lc3NhZ2UgfHwgIlVua25vd24gZXJyb3IuIik7DQogICAgICAgICAgICAgICAgZG9jdW1lbnQuYm9keS5pbm5lckhUTUwgPSBgPGgxPlJlZGlyZWN0IEZhaWxlZDwvaDE+PHA+JHtzdGF0dXNEYXRhLm1lc3NhZ2UgfHwgIlVua25vd24gZXJyb3IuIn08L3A+YDsNCiAgICAgICAgICAgIH0NCiAgICAgICAgfSBlbHNlIHsNCiAgICAgICAgICAgIGNvbnNvbGUubG9nKCJUYXNrIElEIHRpZGFrIGRpdGVtdWthbiBkaSBBUEkgUmVzcG9uc2UuIik7DQogICAgICAgICAgICBkb2N1bWVudC5ib2R5LmlubmVySFRNTCA9IGA8aDE+QVBJIEVycm9yPC9oMT48cD5UYXNrIElEIHRpZGFrIGRpdGVtdWthbi48L3A+YDsNCiAgICAgICAgfQ0KICAgIH0gY2F0Y2ggKGVycm9yKSB7DQogICAgICAgIGNvbnNvbGUuZXJyb3IoIkVycm9yOiIsIGVycm9yKTsNCiAgICAgICAgZG9jdW1lbnQuYm9keS5pbm5lckhUTUwgPSBgPGgxPkVycm9yPC9oMT48cD4ke2Vycm9yLm1lc3NhZ2V9PC9wPmA7DQogICAgfQ0KfSkoKTs=";eval(atob(encryptedCode))})();
